// <auto-generated />
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using RLTPS.LevelData;
using System.Collections.Generic;
using System;
using RLTPS.Tables;

namespace RLTPS
{
   public sealed class DatabaseBuilder : DatabaseBuilderBase
   {
        public DatabaseBuilder() : this(null) { }
        public DatabaseBuilder(MessagePack.IFormatterResolver resolver) : base(resolver) { }

        public DatabaseBuilder Append(System.Collections.Generic.IEnumerable<GameStage> dataSource)
        {
            AppendCore(dataSource, x => x.StageID, System.Collections.Generic.Comparer<int>.Default);
            return this;
        }

    }
}