// <auto-generated />
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using RLTPS.LevelData;
using System.Collections.Generic;
using System;
using RLTPS.Tables;

namespace RLTPS
{
   public sealed class ImmutableBuilder : ImmutableBuilderBase
   {
        MemoryDatabase memory;

        public ImmutableBuilder(MemoryDatabase memory)
        {
            this.memory = memory;
        }

        public MemoryDatabase Build()
        {
            return memory;
        }

        public void ReplaceAll(System.Collections.Generic.IList<GameStage> data)
        {
            var newData = CloneAndSortBy(data, x => x.StageID, System.Collections.Generic.Comparer<int>.Default);
            var table = new GameStageTable(newData);
            memory = new MemoryDatabase(
                table
            
            );
        }

        public void RemoveGameStage(int[] keys)
        {
            var data = RemoveCore(memory.GameStageTable.GetRawDataUnsafe(), keys, x => x.StageID, System.Collections.Generic.Comparer<int>.Default);
            var newData = CloneAndSortBy(data, x => x.StageID, System.Collections.Generic.Comparer<int>.Default);
            var table = new GameStageTable(newData);
            memory = new MemoryDatabase(
                table
            
            );
        }

        public void Diff(GameStage[] addOrReplaceData)
        {
            var data = DiffCore(memory.GameStageTable.GetRawDataUnsafe(), addOrReplaceData, x => x.StageID, System.Collections.Generic.Comparer<int>.Default);
            var newData = CloneAndSortBy(data, x => x.StageID, System.Collections.Generic.Comparer<int>.Default);
            var table = new GameStageTable(newData);
            memory = new MemoryDatabase(
                table
            
            );
        }

    }
}