// <auto-generated />
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using RLTPS.LevelData;
using System.Collections.Generic;
using System;

namespace RLTPS.Tables
{
   public sealed partial class GameStageTable : TableBase<GameStage>, ITableUniqueValidate
   {
        public Func<GameStage, int> PrimaryKeySelector => primaryIndexSelector;
        readonly Func<GameStage, int> primaryIndexSelector;


        public GameStageTable(GameStage[] sortedData)
            : base(sortedData)
        {
            this.primaryIndexSelector = x => x.StageID;
        }


        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public GameStage FindByStageID(int key)
        {
            var lo = 0;
            var hi = data.Length - 1;
            while (lo <= hi)
            {
                var mid = (int)(((uint)hi + (uint)lo) >> 1);
                var selected = data[mid].StageID;
                var found = (selected < key) ? -1 : (selected > key) ? 1 : 0;
                if (found == 0) { return data[mid]; }
                if (found < 0) { lo = mid + 1; }
                else { hi = mid - 1; }
            }
            return ThrowKeyNotFound(key);
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public bool TryFindByStageID(int key, out GameStage result)
        {
            var lo = 0;
            var hi = data.Length - 1;
            while (lo <= hi)
            {
                var mid = (int)(((uint)hi + (uint)lo) >> 1);
                var selected = data[mid].StageID;
                var found = (selected < key) ? -1 : (selected > key) ? 1 : 0;
                if (found == 0) { result = data[mid]; return true; }
                if (found < 0) { lo = mid + 1; }
                else { hi = mid - 1; }
            }
            result = default;
            return false;
        }

        public GameStage FindClosestByStageID(int key, bool selectLower = true)
        {
            return FindUniqueClosestCore(data, primaryIndexSelector, System.Collections.Generic.Comparer<int>.Default, key, selectLower);
        }

        public RangeView<GameStage> FindRangeByStageID(int min, int max, bool ascendant = true)
        {
            return FindUniqueRangeCore(data, primaryIndexSelector, System.Collections.Generic.Comparer<int>.Default, min, max, ascendant);
        }


        void ITableUniqueValidate.ValidateUnique(ValidateResult resultSet)
        {
            ValidateUniqueCore(data, primaryIndexSelector, "StageID", resultSet);       
        }

        public static MasterMemory.Meta.MetaTable CreateMetaTable()
        {
            return new MasterMemory.Meta.MetaTable(typeof(GameStage), typeof(GameStageTable), "GameStage",
                new MasterMemory.Meta.MetaProperty[]
                {
                    new MasterMemory.Meta.MetaProperty(typeof(GameStage).GetProperty("StageID")),
                    new MasterMemory.Meta.MetaProperty(typeof(GameStage).GetProperty("BallSpeed")),
                    new MasterMemory.Meta.MetaProperty(typeof(GameStage).GetProperty("BarSpeed")),
                    new MasterMemory.Meta.MetaProperty(typeof(GameStage).GetProperty("BlockPattern")),
                },
                new MasterMemory.Meta.MetaIndex[]{
                    new MasterMemory.Meta.MetaIndex(new System.Reflection.PropertyInfo[] {
                        typeof(GameStage).GetProperty("StageID"),
                    }, true, true, System.Collections.Generic.Comparer<int>.Default),
                });
        }
    }
}